version: 2

jobs:
  node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - node12

notify:
  webhooks:
    - url: https://bot.suddi.io/hooks/circle